# Generated by Django 5.0.1 on 2024-02-18 12:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0001_initial'),
        ('paymentapp', '0002_rename_payment_bool_payment_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='paymentapp.payment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 2, 24)),
        ),
    ]
