# Generated by Django 5.0.1 on 2024-02-09 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 2, 15)),
        ),
    ]
