# Generated by Django 5.0.1 on 2024-02-10 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0002_alter_order_estimated_delivery_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Total_amount',
            new_name='total_amount',
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 2, 16)),
        ),
    ]
