# Generated by Django 5.0.1 on 2024-02-10 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0006_remove_saveforlater_quantity'),
        ('orderapp', '0003_rename_order_id_order_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartapp.cart'),
        ),
    ]
