# Generated by Django 5.0.1 on 2024-02-10 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0005_alter_cartitems_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saveforlater',
            name='quantity',
        ),
    ]
