# Generated by Django 5.0.1 on 2024-02-18 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_bool',
            new_name='is_paid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_checkout_id',
        ),
    ]
