# Generated by Django 5.0.1 on 2024-02-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0002_rename_payment_bool_payment_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_paid',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='client_secret',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
