# Generated by Django 5.0.1 on 2024-02-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Quantity', models.IntegerField()),
                ('Stock_Status', models.CharField(default='OUT_OF_STOCK', max_length=12)),
                ('Color', models.CharField(max_length=20)),
                ('Description', models.TextField(blank=True, max_length=500)),
                ('Rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('Arrival', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
