# Generated by Django 5.0.1 on 2024-02-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('stock_status', models.CharField(default='OUT_OF_STOCK', max_length=12)),
                ('color', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
