# Generated by Django 5.0.1 on 2024-02-06 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Estimated_delivery_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 2, 12)),
        ),
        migrations.AddField(
            model_name='product',
            name='Arrival',
            field=models.DateTimeField(default=datetime.date(2024, 2, 6)),
        ),
    ]
