# Generated by Django 5.0.1 on 2024-02-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_alter_product_arrival_cart_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Arrival',
            field=models.DateField(auto_now=True),
        ),
    ]
