# Generated by Django 5.0.1 on 2024-02-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0003_alter_product_arrival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Estimated_delivery_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Arrival',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
