# Generated by Django 5.0.1 on 2024-02-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0004_alter_order_estimated_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Estimated_delivery_date',
            field=models.DateField(blank=True),
        ),
    ]
