# Generated by Django 5.0.1 on 2024-02-06 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0005_alter_order_estimated_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Estimated_delivery_date',
        ),
    ]
