# Generated by Django 5.0.1 on 2024-02-06 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0006_remove_order_estimated_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Arrival',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
