# Generated by Django 5.0.1 on 2024-02-06 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0008_product_arrival_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Arrival',
        ),
    ]
