# Generated by Django 5.0.1 on 2024-02-06 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_alter_user_timeofregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='TimeOfRegister',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
