# Generated by Django 5.0.1 on 2024-02-06 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_alter_user_timeofregister'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='TimeOfRegister',
        ),
    ]
